server:
  port: 8000
  servlet:
    application-display-name: display
spring:
  application:
    name: service

eureka:
  instance:
    hostname: peer
  client:
    service-url:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/
    fetch-registry: false
    register-with-eureka: false

  server:
    wait-time-in-ms-when-sync-empty: 0
